on:
  push:
    branches:
      - main # Ubah ke 'master' jika branch utama Anda bernama master

name: Deploy website on push

jobs:
  web-deploy:
    name: Deploy ke cPanel
    runs-on: ubuntu-latest
    steps:
      - name: Mengambil kode terbaru
        uses: actions/checkout@v4

      - name: Sinkronisasi file ke hosting
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: 103.93.191.25
          username: kkpsamudrahostin
          password: 123!@#Gamb!r2026KKP
          server-dir: /home/kkpsamudrahostin/repositoris/program-prioritas-budidaya-tematik/
