name: Deploy via SFTP
on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: Deploy ke cPanel
    runs-on: ubuntu-latest
    steps:
      - name: Ambil kode terbaru
        uses: actions/checkout@v4

      - name: Sinkronisasi file ke cPanel via SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local_path: "./*"
          remote_path: "/home/kkpsamudrahostin/repositoris/program-prioritas-budidaya-tematik"
          sftpArgs: "-o ConnectTimeout=5"
