name: Deploy via FTP
on:
  push:
    branches:
      - main # Ubah ke 'master' jika default branch Anda adalah master

jobs:
  web-deploy:
    name: Deploy to cPanel
    runs-on: ubuntu-latest
    steps:
      - name: Get latest code
        uses: actions/checkout@v4
        
      - name: Sync files to cPanel
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: ./ # Ini akan mengunggah ke folder yang Anda atur di FTP Account tadi